/* CRIAÇÃO DA DATABASE */
CREATE DATABASE DB_COMERCIO

/* USAR A DATABASE */
USE DB_COMERCIO


CREATE TABLE TB_USUARIO (
	ID_USUARIO INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	SOBRENOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	USUARIO VARCHAR(60) NOT NULL,
	SENHA VARCHAR(32) NOT NULL,
	ATIVO BIT NOT NULL

	CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO),
	CONSTRAINT UN_USUARIO UNIQUE (USUARIO)
);

INSERT INTO TB_USUARIO (NOME, SOBRENOME, EMAIL, USUARIO, SENHA, ATIVO) 
	VALUES ('ADMINISTRADOR', 'SISTEMA', 'ADMINISTRADOR@SISTEMA.COM', 'ADMIN', '73acd9a5972130b75066c82595a1fae3', 1) /*Senha: ADMIN*/