/* CRIAÇÃO DA DATABASE */
CREATE DATABASE DB_COMERCIO

/* USAR A DATABASE */
USE DB_COMERCIO


CREATE TABLE TB_PESSOA (
	ID_PESSOA INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	SOBRENOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	SEXO CHAR (1) NOT NULL,
	TELEFONE VARCHAR(9) NOT NULL,
	EMAIL VARCHAR(50)

	CONSTRAINT PK_ID_PESSOA PRIMARY KEY (ID_PESSOA),
	CONSTRAINT CH_SEXO CHECK (SEXO IN('F','M')),
	CONSTRAINT UN_CPF UNIQUE (CPF)
);